header: "bot menu."
footer: |
  —
  {prefix}help <command>

categoryHeader: "{category}"
commandItem: "· {command}"

categoryLabels:
  Utils: "general"
  Admins: "admin"
  Dev: "developer"

categoriesOrder:
  - "Utils"
  - "Admins"
  - "Dev"
