header: "· · · *{botName} MENU* · · ·"
footer: |
  · · · · · · · · · · ·
    {prefix}help <command>

categoryHeader: "✦ *{category}*"
commandItem: "  › {command}"

categoryLabels:
  Main: "MAIN"
  Utils: "GENERAL"
  Admins: "ADMIN"
  Dev: "DEVELOPER"

categoriesOrder:
  - "Main"
  - "Utils"
  - "Admins"
  - "Dev"
